series: github-ci-integration-test
artifact_storage_uri: /home/runner/work/arguseyes-example/mlruns/

pipeline:
  template: classification
  path: /home/runner/work/arguseyes-example/arguseyes-example/paper-example.py
  args:
    - Digital_Video_Games
    - !!str 2015-07-31
  working_directory: /home/runner/work/arguseyes-example/arguseyes-example
  detect_issues:
    - constant_features
    - unnormalised_features
    - label_shift
    - covariance shift
    - traintest_overlap
