series: development
artifact_storage_uri: /home/runner/work/arguseyes-example/mlruns/

pipeline:
  path: /home/runner/work/arguseyes-example/arguseyes-example/pipelines/mlinspect-computervision-sneakers.py
  template: classification
  detect_issues:
    - issue:
        name: label_errors
        params:
          max_fraction: 0.03
