series: development
artifact_storage_uri: /__w/arguseyes-example/arguseyes-example/mlruns/

pipeline:
  template: classification
  path: /__w/arguseyes-example/arguseyes-example/pipelines/openml-classification-incomelevel.py
  detect_issues:
    - issue:
        name: fairness
        params:
          sensitive_attribute: sex
          privileged_class: Male
          metric: equal_opportunity
          max_difference: 0.01
    - issue:
        name: fairness
        params:
          sensitive_attribute: race
          privileged_class: White
          metric: statistical_parity
          max_difference: 0.02